# Generated by Django 2.2.7 on 2019-11-20 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips_daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_city', to='trip.Cities_dir')),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_country', to='trip.Countries_dir')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_city', to='trip.Cities_dir')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_country', to='trip.Countries_dir')),
            ],
        ),
    ]
