# Generated by Django 2.2.7 on 2019-12-18 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(blank=True, max_length=250, verbose_name='Оставьте комментарий')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Profile')),
            ],
        ),
    ]
