# Generated by Django 2.2.7 on 2019-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips_daily',
            name='trip_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trips_daily',
            name='date_posted',
            field=models.DateTimeField(),
        ),
    ]
