# Generated by Django 2.2.7 on 2019-11-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20191123_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips_daily',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
