# Generated by Django 2.2.7 on 2019-11-24 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trips_daily_sttlemet_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips_daily',
            name='sttlemet_day',
        ),
        migrations.AddField(
            model_name='trips_daily',
            name='city_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
