# Generated by Django 2.2.7 on 2019-11-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20191124_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips_daily',
            name='city_code',
        ),
    ]
