# Generated by Django 2.2.7 on 2019-12-20 10:35

from django.db import migrations, models
import trip.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20191220_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=250, validators=[trip.validators.clean_comment_text]),
        ),
    ]
