# Generated by Django 2.2.7 on 2019-11-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trips_daily_settle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips_daily',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trips_daily',
            name='settle_date',
            field=models.DateTimeField(verbose_name='Дата поездки'),
        ),
    ]
