# Generated by Django 2.2.7 on 2019-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_auto_20191125_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips_daily',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Опсание'),
        ),
        migrations.AlterField(
            model_name='trips_daily',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Цена'),
        ),
    ]
