# Generated by Django 2.2.7 on 2019-12-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_trips_daily_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips_daily',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
    ]
