# Generated by Django 2.2.7 on 2019-12-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20191220_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
