# Generated by Django 2.2.7 on 2019-12-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_auto_20191208_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips_daily',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена'),
        ),
    ]
