# Generated by Django 2.2.7 on 2019-12-14 10:53

from django.db import migrations, models
import trip.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_auto_20191208_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='trips_daily',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[trip.validators.clean_price], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='trips_daily',
            name='settle_date',
            field=models.DateTimeField(validators=[trip.validators.clean_settle_date], verbose_name='Дата поездки'),
        ),
    ]
